# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2e95ea8b0e6cf116f57f3328f2fe0b2c64fd96cbd75461f12dda6caf0f4cb244b0737f56a2390a7c0cbe48c6c36a0341b01369cf1df3f4ebe3d9d90fd48da15

test:
  secret_key_base: bb0c65faec1f7ad79bb5330dd36b5a2618552026a32799704fe6da0cea5519a2a7d3bb87b9623fed20f8adbd41b75b5b7c77b508d0b8f431ac7cc981170a36ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
